### ISSUE TITLE
Convert To-do list into Github Projects

### ISSUE THREAD

**Issue by Gui-FernandesBR** [Projeto-Jupiter/RocketPy#124]
Current TODO.md list is outdated, we might transfer main topics to github project in order to facilitate our management and then we discuss if we keep TODO.md on our repository or not

**Comment by giovaniceotto** [comment]
Feel free to delete/archive old projects which haven't being used in a while.

**Comment by Gui-FernandesBR** [comment]
I just implemented all important items from TODO.md into project "RocketPy action log",
In the near future we may remove TODO.md file from our repository in order to have only a single source of truth

**Comment by Gui-FernandesBR** [comment]
Also, now our project also has issues and Pull Rquests from the famous Projeto-Jupiter/Hackathon repository, hope this will help us to improve RocketPy funcionalities faster

**Comment by giovaniceotto** [comment]
@Gui-FernandesBR, can we close this?

**Comment by Gui-FernandesBR** [comment]
Sure thing!

Github project give us a way better view than the old TODO.md file. Let's rock!!

![image](https://user-images.githubusercontent.com/63590233/153761549-b19c1c47-4dca-40f3-918a-8b2ce817eb01.png)
