### ISSUE TITLE
Distances vs. Positions...

### ISSUE THREAD

**Issue by giovaniceotto** [Projeto-Jupiter/RocketPy#158]
**Is your feature request related to a problem? Please describe.**

RocketPy's Rocket class arguments can be quite confusing, especially distances (`distanceRocketNozzle`, `distanceRocketPropellant`, `distanceToCM`).

**Describe the solution you'd like**

A new way of entering the position of interest points. It would be extremely nice if you could choose the origin, instead of it being fixed in the center of dry mass.

Furthermore, the naming of center of mass should change to center of dry mass.

**Additional context**

Measuring things using the nose cone as the origin may be easier sometimes!

**Comment by Gui-FernandesBR** [comment]
@MateusStano do you accept this challenge? 

(Of course we will help you along this journey...)

**Comment by MateusStano** [comment]
Challenge accepted and completed!! See --> #195
